SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A
LEFT JOIN ITEM_TREE B 
 ON A.ITEM_ID = B.ITEM_ID
WHERE B.PARENT_ITEM_ID IN (
    SELECT ITEM_ID FROM ITEM_INFO 
    WHERE RARITY = 'RARE'
)
AND B.PARENT_ITEM_ID IS NOT NULL
GROUP BY A.ITEM_ID
ORDER BY ITEM_ID DESC