SELECT 
YEAR(A.DIFFERENTIATION_DATE) YEAR,
(C.MAX_C - A.SIZE_OF_COLONY) YEAR_DEV,
A.ID
FROM 
ECOLI_DATA A 
JOIN
(
 SELECT MAX(SIZE_OF_COLONY) MAX_C, YEAR(DIFFERENTIATION_DATE) DATE
 FROM ECOLI_DATA 
 GROUP BY DATE
) C
ON YEAR(A.DIFFERENTIATION_DATE) = C.DATE
ORDER BY 
YEAR(A.DIFFERENTIATION_DATE) ASC, 
YEAR_DEV ASC
;