-- 코드를 입력하세요
# SELECT TITLE, UGB.BOARD_ID, REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS, DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
# FROM USED_GOODS_BOARD AS UGB, USED_GOODS_REPLY AS UGR
# WHERE UGB.BOARD_ID = UGR.BOARD_ID AND UGB.CREATED_DATE LIKE "2022-10%"
# ORDER BY UGR.WRITER_ID, TITLE;
SELECT TITLE, a.BOARD_ID, REPLY_ID, b.WRITER_ID, b.CONTENTS, DATE_FORMAT(b.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
From USED_GOODS_BOARD as a, USED_GOODS_REPLY as b
where  a.BOARD_ID = b.BOARD_ID
and a.CREATED_DATE LIKE "2022-10%"
order by b.CREATED_DATE,TITLE