-- 코드를 입력하세요
SELECT A.CATEGORY AS CATEGORY, SUM(B.SALES) AS TOTAL_SALES
FROM BOOK A
INNER JOIN BOOK_SALES B
 ON A.BOOK_ID = B.BOOK_ID
WHERE B.SALES_DATE 
BETWEEN TO_DATE('20220101', 'YYYY-MM-DD') AND TO_DATE('20220131', 'YYYY-MM-DD') 
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY ASC
;